# Production environment specific values
# Overrides default values.yaml

kube-prometheus-stack:
  # CRITICAL: Disable admission webhooks - they cause infinite PreSync hooks
  prometheusOperator:
    admissionWebhooks:
      enabled: false
  
  prometheus:
    prometheusSpec:
      replicas: 2
      retention: 30d

      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          cpu: 1000m
          memory: 4Gi

      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi

      # HA Configuration
      podAntiAffinity: "hard"
      
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    alertmanagerSpec:
      replicas: 3

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi

      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 5Gi

      # HA Configuration - spread across nodes
      podAntiAffinity: "hard"

  grafana:
    replicas: 2
    
    adminPassword: "ProductionSecurePassword2024!"
    
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi

    persistence:
      enabled: true
      size: 10Gi

    service:
      type: NodePort
      nodePort: 31300

    # HA Configuration
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                    - grafana
            topologyKey: "kubernetes.io/hostname"

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://monitoring-prod-kube-prome-prometheus.monitoring:9090
            access: proxy
            isDefault: true

  # Node exporter configuration
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: true
      mountPropagation: HostToContainer

  # Kube-state-metrics configuration
  kube-state-metrics:
    resources:
      requests:
        cpu: 20m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
