# Development environment specific values
# Overrides default values.yaml

kube-prometheus-stack:
  # CRITICAL: Disable admission webhooks - they cause infinite PreSync hooks
  prometheusOperator:
    admissionWebhooks:
      enabled: false
  
  prometheus:
    prometheusSpec:
      replicas: 1
      retention: 7d

      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi

      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 10Gi

      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false

  alertmanager:
    alertmanagerSpec:
      replicas: 1

      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 256Mi

      storage:
        volumeClaimTemplate:
          spec:
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 2Gi

  grafana:
    replicas: 1
    
    adminPassword: admin
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

    persistence:
      enabled: true
      size: 5Gi

    service:
      type: NodePort
      nodePort: 30300

    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
          - name: Prometheus
            type: prometheus
            url: http://monitoring-dev-kube-promet-prometheus.monitoring:9090
            access: proxy
            isDefault: true

  # Disable default node exporters on control plane
  prometheus-node-exporter:
    hostRootFsMount:
      enabled: true
      mountPropagation: HostToContainer

  # Kube-state-metrics configuration
  kube-state-metrics:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
