# Sample applications for prod cluster
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kobeep/k8s-devops-template.git
    targetRevision: main
    path: apps/sample-app/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: false  # Manual sync for prod
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
