# Platform components for prod cluster
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kobeep/k8s-devops-template.git
    targetRevision: main
    path: platform/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kobeep/k8s-devops-template.git
    targetRevision: main
    path: platform/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kobeep/k8s-devops-template.git
    targetRevision: main
    path: platform/logging
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: security-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kobeep/k8s-devops-template.git
    targetRevision: main
    path: platform/security
  destination:
    server: https://kubernetes.default.svc
    namespace: security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
